name: dev_challenge_2_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/ElanDeyan/simple-server-dart

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  collection: ^1.19.0
  cryptography: ^2.7.0
  drift: ^2.19.1
  email_validator: ^3.0.0
  path: ^1.9.0
  quiver: ^3.2.1
  random_string_generator: ^2.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.0
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
